### ISSUE TITLE
January 11-17 data collection

### ISSUE THREAD

**Issue by gulmezoglubeyza** [the-normal-lab/digitalproducts#5]
Issue for weekly data collection carried out through January 11-17. 

Remaining to-dos:

- [x] Organize folder/files
- [x] Digitize screenshots & pay bonuses to random set of respondents

**Comment by gulmezoglubeyza** [comment]
### Validating digital time usage 

Hi @u-tkarshd, summarizing the task below:

**Overview:** We recently collected data on which activities people engaged in the day before, whether they would prefer to live in a world with or without them, and how much time (in hours) they spent on them. The hypothesis (which turned out to be true) is people waste a lot of time (>1h per day) on average on things they wish did not exist, and this time largely stems from digital products.

**Task:**  To incentivize truthful reporting, we asked people to upload screenshots of their phone's time usage statistics and said that we will hold a lottery to distribute bonuses for accurate reporting. We now need to digitize said screenshots for two purposes: 
(i) bonuses mentioned above 
(ii) 'validation': checking how accurate their manual reporting was on average. 

**Details:**
- Screenshots: `data/raw/prolific/atus_3steps_random_scrhots/weekly_collection/atus-3steps-random-scrshots_January+19,+2024_04.54` (start from scrshot1)
- Data: `data/temp/digitize_screenshots/atus_3steps_weekly_digitalhours.xls`

**Suggested method:**
- Copy `responseid` from the data column, `cmd + f` in the screenshots folder. 
- Note down time spent in apps that appear in data in a **consistent format**, e.g. Xh Xm. This is to easily convert to hours/minutes to do related analysis. 
- Create a column in a copy excel and note down time spent on apps. 

**Step-by-step:**
- [ ] Digitize screenshots.
- [ ] Convert into consistent format and prepare validation summary (more on this later). 
- [ ] Write down script (in any language) randomly selecting 10 `responseid`s and linking to their corresponding`prolific_pids` (more on this later). 

Comment: Another (cooler) way to do this is to digitize the screenshots via Python. I don't think it will take too much time to do this manually, but let me know after spending ~1h on it so that we have a better idea. I had started a Python script (needs improving) so we can switch to a more sustainable method, if necessary/faster, since the respondents are waiting for their bonuses :)

**Comment by gulmezoglubeyza** [comment]
@u-tkarshd Thanks for your work here! The bonuses have been paid. Thread continues in #6.
